name: OpenRV Build
on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        modules: 'qtwebengine'
    - name: Install linux dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install -y ocl-icd-opencl-dev libglu1-mesa-dev
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRV_DEPS_QT5_LOCATION="$Qt5_DIR"
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
