name: OpenRV Build
on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        modules: 'qtwebengine'
    - name: Install linux dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install -y ocl-icd-opencl-dev libglu1-mesa-dev
    - name: Install macOS dependencies
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install cmake ninja readline sqlite3 xz zlib tcl-tk autoconf automake libtool python yasm clang-format black meson nasm pkg-config glew
    - name: Install windows dependencies
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        pacman -S --needed mingw-w64-x86_64-autotools \
          mingw-w64-x86_64-cmake \
          mingw-w64-x86_64-glew \
          mingw-w64-x86_64-libarchive \
          mingw-w64-x86_64-make \
          mingw-w64-x86_64-meson \
          mingw-w64-x86_64-python-pip \
          mingw-w64-x86_64-python-psutil \
          mingw-w64-x86_64-toolchain \
          bison \
          flex \
          git \
          nasm \
          p7zip \
          unzip \
          zip
    - name: Install python dependencies
      run: python3 -m pip install -r requirements.txt
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRV_DEPS_QT5_LOCATION="$Qt5_DIR" -DRV_DEPS_WIN_PERL_ROOT="/c/Strawberry/perl/bin"
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
